name: Foundry CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-and-test:
    name: Build & Test Raffle Smart Contract
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Install Foundry toolchain
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Step 3: Show Forge version
      - name: Show Forge version
        run: forge --version

      # Step 4: Install project dependencies
      - name: Install Forge dependencies
        run: forge install

      # Step 5: Run code formatter check
      - name: Check formatting
        run: forge fmt --check

      # Step 6: Build contracts and show sizes
      - name: Build contracts
        run: forge build --sizes

      # Step 7: Run all tests
      - name: Run tests
        run: forge test -vvv
